### ISSUE TITLE
Profile delete should delete the profile

### ISSUE THREAD

**Issue by OJFord** [amalucelli/terraform-provider-nextdns#1]
Re:
https://github.com/amalucelli/terraform-provider-nextdns/blob/f2d0029294c882fad4763aabf742908a245fc2f4/nextdns/resource_nextdns_profile.go#L99

Why's that? Create will create it, so removing that resource should then remove it again. This would be the equivalent of create only importing an existing profile, but there's already `terraform import` for that; likewise if 'delete from state only' _is_ what someone wants, there's `terraform state rm` for that.

**Comment by amalucelli** [comment]
This wasn't intentional, probably I added a comment and never looked back as for most of the development I only used a single profile. Thanks for providing a fix for that.

**Comment by OJFord** [comment]
No problem - just caught my eye.

Probably I will too to be honest, apart from the test one I created in making the ID computed; so then did this in order to delete it :smile:.
