### ISSUE TITLE
Release to the Terraform Registry

### ISSUE THREAD

**Issue by amalucelli** [amalucelli/terraform-provider-nextdns#8]
Today is required for the user to build and install the provider locally before consuming the resources it exposes. It's possible to improve this flow by pushing the module to the [Terraform Registry](https://registry.terraform.io/browse/providers) by following [this guide](https://developer.hashicorp.com/terraform/registry/modules/publish).

**Comment by OJFord** [comment]
I can recommend `tfplugindocs` for generating the documentation (in the familiar style from other providers) automatically from the schema too:
https://github.com/hashicorp/terraform-plugin-docs

Happy to help if needed - I have a couple of (small) providers on the registry - but I think basically I did just follow that same guide 🙂.

**Comment by cpressland** [comment]
@amalucelli are you planning to push this to the tf registry anytime soon? This'd be really helpful for one of our workflows but having everybody build the plugin is non-ideal.

**Comment by amalucelli** [comment]
I completely forgot about this, but now it's released to the official Terraform registry.

The provider can be referenced via `amalucelli/nextdns`: https://registry.terraform.io/providers/amalucelli/nextdns/latest

I will work on the documentation of the resources, and other details in the upcoming days.
